apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-gtz3
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dsop-tenant/rhtap-demo-app/hacbs-test-project-gtz3@sha256:8578209f97464e4bb28ae6bd8a590151eb1d62e2953d7f32f1cc3b54dd9f17ac
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
