apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-gtz3
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dsop-tenant/rhtap-demo-app/hacbs-test-project-gtz3@sha256:bc79a6b1529069187852e5fa0ef9dd43a0ea5b4fa90b20bf3214a05be9952e6d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
