apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-gtz3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-gtz3
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-gtz3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-gtz3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-gtz3
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dsop-tenant/rhtap-demo-app/hacbs-test-project-gtz3@sha256:bc79a6b1529069187852e5fa0ef9dd43a0ea5b4fa90b20bf3214a05be9952e6d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
